### ISSUE TITLE
Cannot install your package with pip

### ISSUE THREAD

**Issue by danny305** [sukhbinder/intersection#2]
When I git clone it it works great. However, I am trying to use it in numerous project in different directories and have to keep making copies of the repo for relative imports. When I try: 
 pip3.6 install git+https://github.com/sukhbinder/intersection.git

This is the error message I get. 
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3h/3p51p8wx6ggfqlcmp6nd6ryh0000gn/T/pip-req-build-_vyo17g7/

**Comment by sukhbinder** [comment]
now you can? Please check. Sorry this took so long...
